### ISSUE TITLE
Let CRUD controllers catch `IllegalArgumentException`

### ISSUE THREAD

**Issue by louislai** [CS2103JAN2017-W13-B3/main#119]
Exceptions should not be leaked to the UI. If you wanna test for excepion thrown, write unit tests for itt

**Comment by Melvin-Tan** [comment]
This is same as #75 ?

**Comment by louislai** [comment]
Different. This is more abt internal implementation. #75 is more abt UX

**Comment by louislai** [comment]
Resolved by #153
