### ISSUE TITLE
Support powerful search

### ISSUE THREAD

**Issue by louislai** [CS2103JAN2017-W13-B3/main#135]
@Rinder5 @Melvin-Tan  how?

**Comment by Rinder5** [comment]
do you mean todolist search or command search? todolist search should be relatively simple, just add more parameters to the find method. command search will take a bit more effort to do, but we can work slowly towards it.

**Comment by louislai** [comment]
todo list search. command preview is categorized as good Gui. I'll handle that one

**Comment by louislai** [comment]
what abt search with autocorrect feature. Let's say u search for `completi`. `complete` will be auto changed to `complete` to handle typo

**Comment by Rinder5** [comment]
that one's a lot more ambiguous. cause possibly they may actually be searching for completi. their task descriptions and tags may not actually be full words.

**Comment by louislai** [comment]
what abt searching for both `completi` & `complete`

**Comment by Melvin-Tan** [comment]
Consider the possibility of fuzzy search

**Comment by louislai** [comment]
the definition of fuzzy search is kinda fuzzy

**Comment by Melvin-Tan** [comment]
http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html

even levenshtein distance can be found here wheeeeeeee
there are other fuzzy search algo over here if you are interested

**Comment by louislai** [comment]
@Rinder5 power search can be fuzzy search . how abt we use the stemming libary from apache ntlk so that `complet` searchs for both `complet` & `complete`

**Comment by louislai** [comment]
easy way to get power search feature without wasting time on adding more search parameter
