### ISSUE TITLE
V0.3 Review

### ISSUE THREAD

**Issue by K1ang** [CS2103JAN2017-W13-B3/main#152]
# User Guide
- Interesting introduction!
- Detailed command formats. Keep it up!
- Good job guys. Based on the current progress you are well on your way to meet module expectations of the project. You can proceed further by thinking of how to optimize the UI further. It looks nice and polished, but is it as useful as it can be? Can it show a whole day's schedule at a time? When you add/edit/delete, does it give visual cues to confirm what happened was exactly what user intended?
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- Good to see illustrations on the guide. Keep it up. You can also include illustrations for commands that are more complex. 
# Developer Guide
- More details can be given for some of the components, such as the model component.
- Good job in documenting some of the major design changes you have made and their reasoning. Keep it up!
- Suggested additions:
    - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
    - You can explain other interesting design decisions you made too.

**Comment by louislai** [comment]
Hey @K1ang thanks for the comment! Regarding your comment on undo/redo, I think there is a `Undoable History` section under 3.6 Storage Component.

**Comment by K1ang** [comment]
Ah yes! I read that the `historyStack` with the command history in mind. Maybe you would like to differentiate it a little to make it more distinct. 
And keep it up! 👍
