### ISSUE TITLE
Command format for listing tasks and searching for tasks

### ISSUE THREAD

**Issue by louislai** [CS2103JAN2017-W13-B3/main#16]
So i think it's possible to merge listing tasks and searching for tasks in one single uniform command.

So `list` will display all tasks, while `list study` will tasks which have name with `study` in it

**Comment by Rinder5** [comment]
yeah, its already listed under the find command

**Comment by louislai** [comment]
I must have missed it

**Comment by louislai** [comment]
I think @Melvin-Tan mentioned that `find <term>` would still feel more natural than `list <term>`, that is another opinion as well

**Comment by louislai** [comment]
pr #14
