### ISSUE TITLE
Command format for alias

### ISSUE THREAD

**Issue by louislai** [CS2103JAN2017-W13-B3/main#17]
First I believe the format should be `alias <short-name> <long-command>`

And we can make it slightly flexible

- Allow only aliasing of simple command, e.g `alias ad add` to alias `add` into `ad`
- Allow aliasing a whole phrase, e.g on unix u can do alias v="mvim -v"

The two scenarios are differentiated depending on there are"(quote) or no"`. So i think we can support both scenarios

**Comment by Melvin-Tan** [comment]
Let's go with alias and unalias instead of addalias and removealias. We try to make it single word as much as we can while still maintain the meaning.

**Comment by Melvin-Tan** [comment]
As for double quotes to make args less ambiguous, i agree with this approach.

**Comment by louislai** [comment]
Resolved by pr #14
