### ISSUE TITLE
Merge list & switch commands

### ISSUE THREAD

**Issue by louislai** [CS2103JAN2017-W13-B3/main#54]
Right now we have a `list` command that acts similarly to the `find` command, and `switch` to change between different tabs
How about merging `list` & `switch`. `list` will switch the window the first/default tab. `list` with parameter switches to the desired tab
Relevant UI Mockup #25 

Thoughts @Melvin-Tan @Rinder5

**Comment by Rinder5** [comment]
sounds ok. So list will not act as find anymore, correct?

**Comment by louislai** [comment]
`list` will still display all the default tasks, which is the original reason we wanted it

**Comment by Rinder5** [comment]
then i don't agree.
list should either manipulate ui or filter data, not both.

**Comment by Rinder5** [comment]
If data has already been filtered by find, either list will revert to show everything or swap between the different tabs.

**Comment by louislai** [comment]
ah I see what you mean. Actually you are right, maybe should make list manipulate ui only

**Comment by Rinder5** [comment]
@Melvin-Tan
